webname: "dantri"
task: "type"
article_type: "the-gioi/quan-su"

logger_fpath: "logger/logger_config.yml"
output_dpath: "result/dantri_quansu"

num_workers: 1
total_pages: 3
max_days_old: 30

continuous_mode: true
crawl_interval: 200
use_head_check: true