# Dân Trí - Quân sự
webname: "dantri"

# tasks = ["url", "type"]
task: "type"

#logger config file path
logger_fpath: "logger/logger_config.yml"
urls_fpath: "urls.txt"
output_dpath: "result/dantri_quansu"
num_workers: 2

# Crawl quân sự (subcategory)
article_type: "the-gioi/quan-su"
total_pages: 10

